### ISSUE TITLE
Sleep/Wake

### ISSUE THREAD

**Issue by honeybaj** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#16]
iGPU 5500 device-id problem identical to mancot14 is happening except on an intel i5.

**Comment by honeybaj** [comment]
Followed the fix for the i3 boards to spoof the 6000 and it worked flawlessly. My system is the i5 version with 8gb of ram.

**Comment by TheRandMan** [comment]
Thanks for sharing. I'll test on my i5/8GB that doesn't require it. If I don't see any negative side effects I'll add it to the config as a default.
