### ISSUE TITLE
Upgrading to Big Sur

### ISSUE THREAD

**Issue by jdferron** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#20]
Do you have any plans to upgrade to Big Sur?  If so, will you be updating your documentation?

**Comment by TheRandMan** [comment]
Big Sur should work just fine with the current config. I was on the beta for about 2 months and now on the official release. 

However I do suggest changing the "Misc > Security > SecureBootModel" setting from **Default** to **Disabled** as it did cause an issue updating during one of the beta updates.

I've been a bit busy but will hopefully have time to update the config to the latest OpenCore soon.

**Comment by jdferron** [comment]
Cool!  Thanks!  I will try it out this week!

**Comment by TheRandMan** [comment]
Officially supported with [this merge](https://github.com/TheRandMan/Hackintosh---Dell-Chromebook-13-7310/pull/21)
