### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by KevDoy** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#22]
First of all, @TheRandMan – thank you for a fun project to tinker with during lockdown. I am so grateful you put the time and effort into this. I can't believe how well it works!

I did however run into one issue and that's Bluetooth. My machine just says Bluetooth unavailable. I am using the intel wifi card. Any ideas?

Thanks

**Comment by TheRandMan** [comment]
I was initially shocked at how well it works too! 

As for getting Intel bluetooth working, I don't personally have any experience with it but I think this will get you going:
https://github.com/OpenIntelWireless/IntelBluetoothFirmware

**Comment by KevDoy** [comment]
It's the strangest thing... I plugged in my Apple Trackpad via USB and I got a notification that it can now connect wirelessly. Obviously I thought this was a mistake. A canned notification. But when I unplugged it, it was listed and Bluetooth is working now. I don't get it, but I'll take it.

**Comment by KevDoy** [comment]
PS: I don't see a contribution link on your profile, but I'd love to buy you a beer/coffee for all the work you've put into this.
