### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by KevDoy** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#24]
There is a note that iGPU does not support DRM content on Hackintosh.
I have used an iGPU desktop hacktinosh and DRM worked fine. I wasn't upset that it didn't work on the 7310 when I first set it up.

Today, I started up spotify again, and I don't know why, but it worked. So I fired up Netflix, and that worked, too. Anyone have any idea of what could have changed? Has anyone else experienced this?

Merry Christmas and Happy Holidays

**Comment by TheRandMan** [comment]
If you're using Chrome some (most?) sites with DRM will function but content will only play in standard definition. I think it comes down to whether the DRM is hardware or software based.

Have a look here for more info:
[https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding](https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding)

I think Sandy Bridge was the last generation where hardware DRM was functional.
