### ISSUE TITLE
No Fan Spin

### ISSUE THREAD

**Issue by KevDoy** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#27]
I was recently swapping out my network card when I noticed that there was no fan spin. Did I miss a kext?

**Comment by TheRandMan** [comment]
The fan only spins up when necessary but it is definitely audible when it does spin up. I hear mine every so often.

You might want to run a benchmarking tool to get the temps up and see if the fan is functioning properly. From my understanding, it's controlled by the firmware and not the OS.

**Comment by TheRandMan** [comment]
Also, make sure you're on the latest firmware from MrChromebox. I believe there were fan related issues with our devices on earlier releases.

**Comment by KevDoy** [comment]
Thank you
