### ISSUE TITLE
Trackpad didn't work after wake up from sleep

### ISSUE THREAD

**Issue by yintsyu** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#33]
I have installed the 10.15.7 Catalina. When I turn on the laptop normally, everything works fine. But if I wake up the laptop from sleep, the trackpad doesn't work.

I tried changing the hibernatemode but it didn't help.

**Comment by TheRandMan** [comment]
Is this on 4.13 firmware?

**Comment by yintsyu** [comment]
No, I'm using 4.12 firmware.

**Comment by TheRandMan** [comment]
Which trackpad kext are you using? VoodooI2CSynaptics or VoodooRMI?

Either way, this is an issue with the trackpad kext and you might want to try switching to whichever one you aren't using.
