### ISSUE TITLE
Stuck at Apple logo, bootloop in verbose

### ISSUE THREAD

**Issue by catfamily121** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#36]
Hello!
This is my first Github issue, so forgive if the format is wrong as i didn't find one for this repo.
I recently got a Dell Chromebook 13 7310 (LULU) as it was cheap enough on amazon and I wanted MacOS on a Chromebook just because I have way to much time on my hands and stuff like this interests me. I will attach a photo of the screen before it reboots. I should also mention that I changed HfsPlus.efi to HfsPlusLegacy.efi and renamed it to fit my config.plist, and I also changed my 
config.plist NVRAM quirks according to [this](https://www.reddit.com/r/hackintosh/comments/gn41rk/comment/frfx5wu/?utm_source=share&utm_medium=web2x&context=3) reddit post. I have also cleaned my SMBIOS any help would be appreciated!
[EFI.zip](https://github.com/one8three/Hackintosh---Dell-Chromebook-13-7310/files/10904150/EFI.zip)
![20230306_195619](https://user-images.githubusercontent.com/124477943/223291702-022da8bb-f5a3-4183-ae4b-242cd9c7e480.jpg)

**Comment by catfamily121** [comment]
Closing as I found a fix that spoofed the CPU as Ivy Bridge, see [this issue](https://github.com/acidanthera/bugtracker/issues/365) for more information.

**Comment by megatronskneecap** [comment]
Tysm! I've got a Jasperlake Machine i'm trying to get up and running too. I think this will help.
