### ISSUE TITLE
i3-5005u HD 5500

### ISSUE THREAD

**Issue by mankot14** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#4]
For i3-5005u variants, the current config.plist leads to a kernel panic or hang at IGPU injection. The message should read something like "[IGPU] Scheduler Throttle Cap 100ms". We need a specific device property added for Intel HD 5500 graphics to be correctly injected at first boot up.
![Screen Shot 2020-06-23 at 11 12 08 AM](https://user-images.githubusercontent.com/39076224/85421779-d2f59400-b542-11ea-8db7-b2ccd183de51.png)

-14irahtom on reddit

**Comment by TheRandMan** [comment]
Great find! Glad you got it working. I'm curious if you've tried using just AAPL,ig-platform-id with 02001616? Leaving out framebuffer-patch-enable and device-id. 

According to the dortania guide, that's how I should've had it set to begin with.

**Comment by mankot14** [comment]
Trying just the AAPL,ig-platform-id hung up/gave a KP. I actually just tried just the two lines without framebuffer-patch-enable and it worked fine! I read a few forums that said that SOME variants of the HD 5500 (mainly the i3-5005u) required the device-id either faked or entered. The Dortania guide singles out only the HD 5600 needing device-id but it seems it applies to our IGPU as well.

**Comment by TheRandMan** [comment]
Good to know! Any chance that fixed the issue of the display staying black after sleep?

**Comment by mankot14** [comment]
Just tried that and booting broke again. I'm hoping to find a fix for wake from sleep soon - it's really the only thing left now to make this a daily driver.

**Comment by TheRandMan** [comment]
Bummer! I'm going to create a new config for the i3 model with the AAPL,ig-platform-id and device-id that you found to work. I'll close out this issue and leave the black screen wake issue open. If you find a fix please share! I'll research a bit too.

Thanks for this fix!

**Comment by TheRandMan** [comment]
@mankot14 are you using all of the included DSDT/SSDTs and kexts? Or did you need to change anything else in the config?

**Comment by mankot14** [comment]
Yeah I'm using all the included files in ACPI and Kexts folders (except the Dell Wireless card stuff). Everything is the same but I needed to make that one change to get graphics working. I PMd the guy on r/hackintosh who posted a successful install on his i3 8GB machine which is identical to mine - I asked for his config.plist and EFI structure but he directed me back to you lol. I don't understand how he didn't need to change anything...

**Comment by TheRandMan** [comment]
How odd. Maybe possible revisions to the motherboard? I popped mine open and didn't see any revision markings on the board but there is one on a sticker on the inside of the bottom plate. Unfortunately my bottom plate isn't original so I don't know what my actual revision number is. Maybe see if the guy on r/hackintosh can compare revision numbers with you.
