### ISSUE TITLE
i3-5005u HD 5500 Wake from Sleep

### ISSUE THREAD

**Issue by mankot14** [TheRandMan/Hackintosh---Dell-Chromebook-13-7310#5]
The displays goes to a black backlit screen during the following scenarios:
- After opening the lid and pressing a key
- Putting the laptop to sleep using the GUI
- After unlocking using Apple Watch

Despite the black backlit screen, I confirmed that the keyboard and sound work (trackpad not confirmed since I can't see the display).
I'm assuming that once again, this has to do with the i3-5005u variant Intel HD 5500. Looking for a solution...

-14irahtom (on reddit)

**Comment by TheRandMan** [comment]
Certainly sounds like a graphics issue. You've likely found the graphics injection section of the dortania guide but if not, some stuff here may help [https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/broadwell.html#pciroot0x0pci0x20x0](https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/broadwell.html#pciroot0x0pci0x20x0)

**Comment by mankot14** [comment]
Would you mind sharing the PM settings with me? I'm attaching mine to compare...
![Screen Shot 2020-06-24 at 2 09 52 PM](https://user-images.githubusercontent.com/39076224/85609841-78ccff80-b624-11ea-8232-7cf47267c098.png)

**Comment by TheRandMan** [comment]
![Screen Shot 2020-06-24 at 11 27 00 AM](https://user-images.githubusercontent.com/33759959/85612370-a9ee0580-b60d-11ea-8f98-6b11127265f5.png)

Looks like you might've missed the post-install step to disable hibernate. It wasn't in an obvious spot in the readme. I moved it so it's more noticeable now. 

Run this command in terminal `sudo pmset -a hibernatemode 0`

I'm somewhat hopeful that'll fix the issue.

**Comment by mankot14** [comment]
Thanks for sharing that - unfortunately didn't work. I remember doing that immediately after but somehow got switched back. Would you mind emailing me the config.plist you're using in your final install in the EFI?

**Comment by TheRandMan** [comment]
Darn! Here's the config.plist straight from my EFI with SMBIOS removed. It should be mostly identical to the one in the repo. It does add the GPU section under Device Properties but I haven't noticed any difference with or without that.


[config.plist.zip](https://github.com/TheRandMan/Hackintosh---Dell-Chromebook-13-7310/files/4827611/config.plist.zip)

**Comment by mankot14** [comment]
FIXED!! 
![Screen Shot 2020-06-24 at 3 54 45 PM](https://user-images.githubusercontent.com/39076224/85621288-0879aa80-b633-11ea-8580-063321493ea5.png)

Everything works now! You're right it was nothing in the config.plist except for the wrong ig-platform-id. Found a post by RehabMan for Clover that clearly stated that i3-5005u HD 5500s NEED the device-id. On top of that he posted several id-platform-id's that work. I was using the wrong one all along...

Perhaps you could create a separate i3 config in your repo and in the readme add a blurb about how some unfortunate ones like me might need a different config.plist.

**Comment by mankot14** [comment]
s

**Comment by TheRandMan** [comment]
Awesome! Glad you finally got it working properly. I'll make a new alternate i3 config file with the ig-platform-id you mentioned.

Yeah very odd that the other guy doesn't have the same issues. I guess that's the world of hackintoshing lol. 

Anyway, enjoy MacOS!
